---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      yum:
        name:
          - python-pip
        state: latest
        update_cache: true
        
    - name: Install Docker SDK for Python
      pip:
        name: "docker<5" 
      become: yes

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      shell: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 230601024369.dkr.ecr.ap-south-1.amazonaws.com
    
    - name: deploy docker container
      docker_container:
        name: javatest
        image: 230601024369.dkr.ecr.ap-south-1.amazonaws.com/javatest:latest
        state: present
        ports:
          - "8080:80"
