---
- hosts: all
  become: True
  tasks:
    - name: Install Docker
      yum:
        name:
          - python-pip
        state: latest
        update_cache: true
        
    - name: "Download war file"
      maven_artifact:
        group_id: com.domain
        artifact_id: demo
        extension: war
        version: 2.0.1-SNAPSHOT
        repository_url: "http://15.206.186.85:8081/repository/maven-test-repo/"
        username: admin
        password: admin
        dest: "/tmp/ROOT.war"
        mode: '0644'
