---
- hosts: all
  become: True
  tasks:
    - name: Install lxml
      pip: name=lxml
      
    - name: "Download war file"
      maven_artifact:
        group_id: com.domain
        artifact_id: demo
        extension: war
        version: "{{ VersionToDeploy }}"
        repository_url: "http://15.206.186.85:8081/repository/maven-test-repo/"
        username: admin
        password: admin
        dest: "/tmp/demo.war"
        mode: '0644'
