---
- hosts: all
  become: True
  tasks:    
    - name: Install lxml
      pip: name=lxml
      
    - name: "Download war file"
      maven_artifact:
        group_id: com.domain
        artifact_id: demo
        extension: war
        version: '{{ version }}'
        repository_url: "http://15.206.186.85:8081/repository/maven-test-repo/"
        username: admin
        password: admin
        dest: "/tmp/demo.war"
        mode: '0644'
     
    - name: download tomcat server packages
      get_url:
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.44/bin/apache-tomcat-9.0.44.tar.gz
        dest: /usr/local

    - name: extract tomcat packages
      unarchive:
        src: /usr/local/apache-tomcat-9.0.44.tar.gz
        dest: /usr/local
        remote_src: yes
  
    - name: Copy the war file  
      copy:  
        src: /tmp/demo.war  
        dest: /usr/local/apache-tomcat-9.0.44/webapps/ 
        remote_src: yes

    - name: start tomcat services
      shell: nohup /usr/local/apache-tomcat-9.0.44/bin/startup.sh
